# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Unicode-Overload
version:      0.01
version_from: lib/Unicode/Overload.pm
installdirs:  site
requires:
    Filter::Simple:                0.78

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
